### ISSUE TITLE
Unable to Scroll When Adding Secrets in Online Editor

### ISSUE THREAD

**Issue by shawntax** [auth0/webtasks#4]
Hi Auth0 team,

Found a minor but annoying bug when working with the online WebTask editor. I am unable to scroll after the "Secrets" menu starts overflowing (happens when adding a seventh secret). At that point, the "Add Secret" button becomes unaccessible .

<img width="1917" alt="scroll-bug" src="https://user-images.githubusercontent.com/8904630/45188468-4b158d00-b1e9-11e8-95c6-073f941669c8.png">

**Comment by rwtombaugh** [comment]
Hi @shawntax -- this should now be fixed. Thanks!
